### ISSUE TITLE
What's "icons.AndroidIcons"?

### ISSUE THREAD

**Issue by wenjianxue** [Haehnchen/idea-android-studio-plugin#2]
Hi,I got the project.It's good.But when I try to build in IDEA14.0, it said there isn't "icons.AndroidIcons" that in file "FragmentRelatedFileLineMarker".
Can you tell me how can I find "icons.AndroidIcons"?
Thanks for your job.

**Comment by Haehnchen** [comment]
sry for late response, but just add the android studio libs in your project:
![intellij-android-studio-plugin](https://cloud.githubusercontent.com/assets/1011712/6885111/97488bee-d611-11e4-956d-cb4e9fe2d16c.png)
